export const SATELLITE_TYPE_PROFILES = {
  EO_OPTICAL: {
    platform: "Sun-synchronous LEO",
    orbit_type: "SSO",
    nominal_altitude_km: 500,
    nominal_swath_km: 24,
    revisit_hours: 24,
    sensor_modes: ["NADIR", "OFF_NADIR"],
    default_product_type: "L1B_ORTHOREADY",
    default_bands_or_polarization: ["R", "G", "B", "NIR"],
  },
  SAR: {
    platform: "Low Earth Orbit radar",
    orbit_type: "LEO",
    nominal_altitude_km: 550,
    nominal_swath_km: 30,
    revisit_hours: 12,
    sensor_modes: ["SPOTLIGHT", "STRIPMAP"],
    default_product_type: "GRD",
    default_bands_or_polarization: ["VV", "VH"],
  },
};

export const SATELLITE_BASELINES = [
  {
    system_id: "K-EO-01",
    kor_name: "아리랑 3호",
    eng_model: "KOMPSAT-3",
    domain: "EO",
    resolution_perf: "0.7m optical",
    baseline_status: "운용 중",
    primary_mission: "국토 관리 및 지구 정밀 관측",
  },
  {
    system_id: "K-EO-02",
    kor_name: "아리랑 3A호",
    eng_model: "KOMPSAT-3A",
    domain: "EO/IR",
    resolution_perf: "0.55m optical+IR",
    baseline_status: "운용 중",
    primary_mission: "야간 관측 및 열원 탐지",
  },
  {
    system_id: "K-EO-03",
    kor_name: "아리랑 7호",
    eng_model: "KOMPSAT-7",
    domain: "EO",
    resolution_perf: "0.3m optical",
    baseline_status: "운용 초기",
    primary_mission: "초고해상도 촬영",
  },
  {
    system_id: "K-SAR-01",
    kor_name: "아리랑 5호",
    eng_model: "KOMPSAT-5",
    domain: "SAR",
    resolution_perf: "1.0m radar",
    baseline_status: "운용 중",
    primary_mission: "전천후 지형 관측",
  },
  {
    system_id: "K-SAR-02",
    kor_name: "아리랑 6호",
    eng_model: "KOMPSAT-6",
    domain: "SAR",
    resolution_perf: "0.5m radar",
    baseline_status: "발사 대기",
    primary_mission: "정밀 전천후 감시",
  },
  {
    system_id: "K-GEO-01",
    kor_name: "천리안 2A호",
    eng_model: "GK-2A",
    domain: "GEO-EO",
    resolution_perf: "기상/우주기상",
    baseline_status: "운용 중",
    primary_mission: "24시간 실시간 기상 예보 및 감시",
  },
  {
    system_id: "K-GEO-02",
    kor_name: "천리안 2B호",
    eng_model: "GK-2B",
    domain: "GEO-EO",
    resolution_perf: "해양/대기환경",
    baseline_status: "운용 중",
    primary_mission: "미세먼지 이동 경로 및 해양 환경",
  },
  {
    system_id: "MIL-425-01",
    kor_name: "군 정찰위성 1호",
    eng_model: "425 Project #1",
    domain: "EO/IR",
    resolution_perf: "0.3m class",
    baseline_status: "전력화 완료",
    primary_mission: "대북 전략 표적 주간 정밀 감시",
  },
  {
    system_id: "MIL-425-02",
    kor_name: "군 정찰위성 2호",
    eng_model: "425 Project #2",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "전력화 완료",
    primary_mission: "전천후 대북 감시",
  },
  {
    system_id: "MIL-425-03",
    kor_name: "군 정찰위성 3호",
    eng_model: "425 Project #3",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "운용 중",
    primary_mission: "군집 감시망 구성",
  },
  {
    system_id: "MIL-425-04",
    kor_name: "군 정찰위성 4호",
    eng_model: "425 Project #4",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "운용 중",
    primary_mission: "군집 감시망 구성 (재방문 주기 단축)",
  },
  {
    system_id: "MIL-425-05",
    kor_name: "군 정찰위성 5호",
    eng_model: "425 Project #5",
    domain: "SAR",
    resolution_perf: "0.5m class",
    baseline_status: "운용 초기",
    primary_mission: "2025.11 발사 성공, 체계 완성",
  },
  {
    system_id: "K-CAS-01",
    kor_name: "차세대 중형 1호",
    eng_model: "CAS500-1",
    domain: "EO",
    resolution_perf: "0.5m optical",
    baseline_status: "운용 중",
    primary_mission: "국토 자원 관리",
  },
  {
    system_id: "K-CAS-02",
    kor_name: "차세대 중형 2호",
    eng_model: "CAS500-2",
    domain: "EO",
    resolution_perf: "0.5m optical",
    baseline_status: "발사 예정",
    primary_mission: "2026년 상반기 발사 (재난 대응)",
  },
  {
    system_id: "K-NEON",
    kor_name: "초소형 군집위성",
    eng_model: "NEONSAT",
    domain: "EO",
    resolution_perf: "1.0m class constellation",
    baseline_status: "확장 중",
    primary_mission: "고빈도 재방문 관측",
  },
];

export const SCENARIO_BASELINES = [
  {
    scenario_id: "SCN-001",
    scenario_name: "국토 정사영상 갱신",
    scenario_desc: "K-EO-01, K-CAS-01 기반 정사영상 주기 갱신",
    satellite_system_ids: ["KOMPSAT-3", "CAS500-1"],
  },
  {
    scenario_id: "SCN-002",
    scenario_name: "야간 산불 열원 탐지",
    scenario_desc: "K-EO-02 IR 야간 열원 탐지",
    satellite_system_ids: ["KOMPSAT-3A"],
  },
  {
    scenario_id: "SCN-003",
    scenario_name: "도시변화 탐지",
    scenario_desc: "K-EO-03 초고해상도 변화 분석",
    satellite_system_ids: ["KOMPSAT-7"],
  },
  {
    scenario_id: "SCN-004",
    scenario_name: "홍수지역 SAR 판독",
    scenario_desc: "K-SAR-01 장마철 침수 분석",
    satellite_system_ids: ["KOMPSAT-5"],
  },
  {
    scenario_id: "SCN-005",
    scenario_name: "정밀 레이더 표적 재식별",
    scenario_desc: "K-SAR-02 정밀 SAR 표적 재식별",
    satellite_system_ids: ["KOMPSAT-6"],
  },
  {
    scenario_id: "SCN-006",
    scenario_name: "태풍 실황 추적",
    scenario_desc: "K-GEO-01 기상 연속 감시",
    satellite_system_ids: ["GK-2A"],
  },
  {
    scenario_id: "SCN-007",
    scenario_name: "미세먼지 이동 추적",
    scenario_desc: "K-GEO-02 대기/해양 환경 감시",
    satellite_system_ids: ["GK-2B"],
  },
  {
    scenario_id: "SCN-008",
    scenario_name: "전략표적 EO/IR 감시",
    scenario_desc: "MIL-425-01 주간 정밀 감시",
    satellite_system_ids: ["425-PROJECT-1"],
  },
  {
    scenario_id: "SCN-009",
    scenario_name: "악천후 표적 감시",
    scenario_desc: "MIL-425-02 SAR 감시",
    satellite_system_ids: ["425-PROJECT-2"],
  },
  {
    scenario_id: "SCN-010",
    scenario_name: "SAR 군집 재방문 감시",
    scenario_desc: "MIL-425-03/04/05 군집 감시",
    satellite_system_ids: ["425-PROJECT-3", "425-PROJECT-4", "425-PROJECT-5"],
  },
  {
    scenario_id: "SCN-011",
    scenario_name: "재난 대응 표준 관측",
    scenario_desc: "K-CAS-02 재난 대응",
    satellite_system_ids: ["CAS500-2"],
  },
  {
    scenario_id: "SCN-012",
    scenario_name: "초소형 군집 모니터링",
    scenario_desc: "K-NEON 고빈도 관측",
    satellite_system_ids: ["NEONSAT"],
  },
];

export const GROUND_STATION_PRESETS = [
  ["Daejeon Mission Control Ground Station", "FIXED", "Daejeon"],
  ["Jeju Maritime Satellite Ground Station", "MARITIME", "Jeju"],
  ["Incheon Airborne Relay Ground Station", "AIRBORNE", "Incheon"],
];

export const GROUND_STATION_REQUESTOR_PRESETS = {
  Daejeon: ["Daejeon Requestor Alpha", "Daejeon Requestor Bravo"],
  Jeju: ["Jeju Requestor Alpha", "Jeju Requestor Bravo"],
  Incheon: ["Incheon Requestor Alpha", "Incheon Requestor Bravo"],
};
